Connected to mmsc (Python 3.11.13)

In [ ]:
model = pybamm.lithium_ion.SPM()
parameter_values= pybamm.ParameterValues("Chen2020")
t_eval = np.linspace(0,10,100)
solution = pybamm.Simulation(model, parameter_values=parameter_values).solve(t_eval = t_eval, t_interp=t_eval)
dataset= pybop.import_pybamm_solution(solution)
#---updating parameters----
parameter_values.update({
"Negative electrode active material volume fraction ": pybop.Parameter(initial_value=0.6),

"Positive electrode active material volume fraction": pybop.Parameter(initial_value=0.6),
})

#---using dataset, solution and parameter values(defined above)---#
output_variables = ["Voltage [V]"]
simulator = pybop.pybamm.Simulator(model,
            parameter_values=parameter_values, protocol=dataset, output_variables=output_variables)
inputs = simulator.parameters.to_dict([0.5,0.5])
solution =simulator.solve(inputs=inputs)
#---Defining cost---#

cost=  pybop.SumOfPower(dataset)
cost.evaluate(solution,inputs=inputs)

NameError: name 'pybamm' is not defined

In [ ]:
#-----------preamble-----------#
import numpy as np
import pybamm
import pybop
import scipy as sc
import matplotlib as plt
import os

#%%

In [ ]:
import numpy as np
import pybamm
import pybop
import scipy as sc
import matplotlib as plt
import os

In [ ]:
# ---preamble---#
import numpy as np
import pybamm
import pybop
import scipy as sc
import matplotlib as plt
import os

In [ ]:
model = pybamm.lithium_ion.SPM()
parameter_values= pybamm.ParameterValues("Chen2020")
t_eval = np.linspace(0,10,100)
solution = pybamm.Simulation(model, parameter_values=parameter_values).solve(t_eval = t_eval, t_interp=t_eval)
dataset= pybop.import_pybamm_solution(solution)
#---updating parameters----
parameter_values.update({
"Negative electrode active material volume fraction ": pybop.Parameter(initial_value=0.6),

"Positive electrode active material volume fraction": pybop.Parameter(initial_value=0.6),
})

#---using dataset, solution and parameter values(defined above)---#
output_variables = ["Voltage [V]"]
simulator = pybop.pybamm.Simulator(model,
            parameter_values=parameter_values, protocol=dataset, output_variables=output_variables)
inputs = simulator.parameters.to_dict([0.5,0.5])
solution =simulator.solve(inputs=inputs)
#---Defining cost---#

cost=  pybop.SumOfPower(dataset)
cost.evaluate(solution,inputs=inputs)

np.float64(0.011041151251654108)

In [ ]:
# ----setting up model----
model = pybamm.lithium_ion.SPM()
parameter_values= pybamm.ParameterValues("Chen2020")
t_eval = np.linspace(0,10,100)
solution = pybamm.Simulation(model, parameter_values=parameter_values).solve(t_eval = t_eval, t_interp=t_eval)
dataset= pybop.import_pybamm_solution(solution)
#---updating parameters----
parameter_values.update({
"Negative electrode active material volume fraction ": pybop.Parameter(initial_value=0.6),

"Positive electrode active material volume fraction": pybop.Parameter(initial_value=0.6),
})

#---using dataset, solution and parameter values(defined above)---#
output_variables = ["Voltage [V]"]
simulator = pybop.pybamm.Simulator(model,
            parameter_values=parameter_values, protocol=dataset, output_variables=output_variables)
inputs = simulator.parameters.to_dict([0.5,0.5])
solution =simulator.solve(inputs=inputs)
#---Defining cost---#

cost=  pybop.SumOfPower(dataset)
cost.evaluate(solution,inputs=inputs)

np.float64(0.011041151251654108)

In [ ]:
# --- Problem Object appraoch--
problem = pybop.Problem(simulator,cost)
evaluation = problem.evaluate(inputs)
evaluation.get_values()

array([0.01104115])

In [ ]:
# ----setting up model----
model = pybamm.lithium_ion.SPM()
parameter_values= pybamm.ParameterValues("Chen2020")
t_eval = np.linspace(0,10,100)
solution = pybamm.Simulation(model, parameter_values=parameter_values).solve(t_eval = t_eval, t_interp=t_eval)
dataset= pybop.import_pybamm_solution(solution)
#---updating parameters----
parameter_values.update({
"Negative electrode active material volume fraction ": pybop.Parameter(initial_value=0.6),

"Positive electrode active material volume fraction": pybop.Parameter(initial_value=0.6),
})

#---using dataset, solution and parameter values(defined above)---#
output_variables = ["Voltage [V]"]
simulator = pybop.pybamm.Simulator(model,
            parameter_values=parameter_values, protocol=dataset, output_variables=output_variables)
inputs = simulator.parameters.to_dict([0.5,0.5])
solution =simulator.solve(inputs=inputs)
#---Defining cost---#

cost=pybop.SumOfPower(dataset)
cost.evaluate(solution,inputs=inputs)

np.float64(0.011041151251654108)

In [ ]:
# --- creating custom loss function--with guassian noise --# 

def my_cost(inputs):
    y= simulator.solve(inputs)
    solution = pybop.Solution(inputs)
    solution.set_solution_variable("Voltage [V]", data= pybop.add_noise(y["Voltage [V]"].data, 0.003),)
    return cost.evaluate(solution,inputs)

my_cost(inputs)

AttributeError: module 'pybop' has no attribute 'add_noise'

In [ ]:
# ---preamble---#
import numpy as np
import pybamm
import pybop
import scipy as sc
import matplotlib as plt
import os

In [ ]:
pybop.plot.PlotlyManager().pio.renderers.default = "notebook_connected"
np.random.seed(8)

In [ ]:
# ----setting up model----
model = pybamm.lithium_ion.SPM()
parameter_values= pybamm.ParameterValues("Chen2020")
t_eval = np.linspace(0,10,100)
solution = pybamm.Simulation(model, parameter_values=parameter_values).solve(t_eval = t_eval, t_interp=t_eval)
dataset= pybop.import_pybamm_solution(solution)
#---updating parameters----
parameter_values.update({
"Negative electrode active material volume fraction ": pybop.Parameter(initial_value=0.6),

"Positive electrode active material volume fraction": pybop.Parameter(initial_value=0.6),
})
#---using dataset, solution and parameter values(defined above)---#
output_variables = ["Voltage [V]"]
simulator = pybop.pybamm.Simulator(model,
            parameter_values=parameter_values, protocol=dataset, output_variables=output_variables)
inputs = simulator.parameters.to_dict([0.5,0.5])
solution =simulator.solve(inputs=inputs)
#---Defining cost---#

cost=pybop.SumOfPower(dataset)
cost.evaluate(solution,inputs=inputs)

np.float64(0.011041151251654108)

In [ ]:
# --- Problem Object appraoch--
problem = pybop.Problem(simulator,cost)
evaluation = problem.evaluate(inputs)
evaluation.get_values()

array([0.01104115])

In [ ]:
# ---preamble---#
import numpy as np
import pybamm
import pybop
import scipy as sc
import matplotlib as plt
import os

In [ ]:
pybop.plot.PlotlyManager().pio.renderers.default = "notebook_connected"
np.random.seed(8)

In [ ]:
# ----setting up model----
model = pybamm.lithium_ion.SPM()
parameter_values= pybamm.ParameterValues("Chen2020")
t_eval = np.linspace(0,10,100)
solution = pybamm.Simulation(model, parameter_values=parameter_values).solve(t_eval = t_eval, t_interp=t_eval)
dataset= pybop.import_pybamm_solution(solution)
#---updating parameters----
parameter_values.update({
"Negative electrode active material volume fraction ": pybop.Parameter(initial_value=0.6),

"Positive electrode active material volume fraction": pybop.Parameter(initial_value=0.6),
})
#---using dataset, solution and parameter values(defined above)---#
output_variables = ["Voltage [V]"]
simulator = pybop.pybamm.Simulator(model,
            parameter_values=parameter_values, protocol=dataset, output_variables=output_variables)
inputs = simulator.parameters.to_dict([0.5,0.5])
solution =simulator.solve(inputs=inputs)
#---Defining cost---#

cost=pybop.SumOfPower(dataset)
cost.evaluate(solution,inputs=inputs)

np.float64(0.011041151251654108)

In [ ]:
# --- Problem Object appraoch--
problem = pybop.Problem(simulator,cost)
evaluation = problem.evaluate(inputs)
evaluation.get_values()

array([0.01104115])

In [ ]:
# --- creating custom loss function--with guassian noise --# 

def my_cost(inputs):
    y= simulator.solve(inputs)
    solution = pybop.Solution(inputs)
    solution.set_solution_variable("Voltage [V]", data= pybop.add_noise(y["Voltage [V]"].data, 0.003),)
    return cost.evaluate(solution,inputs)

my_cost(inputs)

AttributeError: module 'pybop' has no attribute 'add_noise'

No kernel connected

In [ ]:
#---sodium ion application--#
model = pybamm.sodium_ion.BasicDFN()
model.print_parameter_info

NameError: name 'pybamm' is not defined

In [ ]:
#---preamble---#
import numpy as np
import scipy as sc
import pybamm
import pybop
import matplotlib as plt
import os

In [ ]:
#---sodium ion application--#
model = pybamm.sodium_ion.BasicDFN()
model.print_parameter_info

<bound method BaseModel.print_parameter_info of <pybamm.models.full_battery_models.sodium_ion.basic_dfn.BasicDFN object at 0x00000280C43FD490>>

In [ ]:
#---sodium ion application--#
model = pybamm.sodium_ion.BasicDFN()
model.print_parameter_info()

┌───────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Parameter                                                 │ Type of parameter                                                                                                                                                                                           │
├───────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Maximum concentration in positive electrode [mol.m-3]     │ Parameter                                                                                                                             

In [ ]:
#--comparing parameters to sodium ion---#
model = pybamm.lithium_ion.DFN()
model.print_parameter_info()

┌───────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Parameter                                                 │ Type of parameter                                                                                                                                                                                           │
├───────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Maximum concentration in positive electrode [mol.m-3]     │ Parameter                                                                                                                             